<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
    if ($exist = $block->getItems()->getSize()) {
        $type = 'related';
        $class = 'accessoires';

        $image = 'product_related_image';
        $title = __('Related Products');
        $items = $block->getItems();
        $limit = 0;
        $shuffle = 0;
        $canItemsAddToCart = $block->canItemsAddToCart();

        $showAddTo = true;
        $showCart = false;
        $templateType = null;
        $description = false;
    }
?>

<?php if ($exist):?>
    <section class="container">
        <div class="row <?php /* @escapeNotVerified */ echo $class; ?>" data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">

        <h2 class="col-sm-12"><?php /* @escapeNotVerified */ echo $title; ?></h2>
            <?php $iterator = 1; ?>
            <?php foreach ($items as $_item): ?>
                <div class="col-sm-4 text-center">
                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                        <p><?php echo $block->escapeHtml($_item->getName()) ?></>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                        <div class="red-button">
                            <?php echo __('en savoir plus'); ?>
                        </div>
                    </a>
                </div>
        <?php endforeach ?>
    </div>
</section>
<?php endif;?>
