<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $currencyManager = $objectManager->create('Magento\Directory\Model\PriceCurrency');
    ?>
    <?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
    <div class="switcher currency switcher-currency" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>">
        <div class="actions dropdown options switcher-options col-sm-6">
            <div class="action toggle switcher-trigger dropdown-toggle" id="switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>">
                <?php echo $currencyManager->getCurrencySymbol(null,$currentCurrencyCode); ?>
                <span class="caret"></span>
            </div>
            <ul class="dropdown switcher-dropdown dropdown-menu" data-mage-init='{"dropdownDialog":{
            "appendTo":"#switcher-currency<?php /* @escapeNotVerified */ echo $id?> > .options",
            "triggerTarget":"#switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "buttons":null}}'>
                <?php foreach ($currencies as $_code => $_name): ?>
                    <?php if ($_code != $currentCurrencyCode): ?>
                        <li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option">
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $currencyManager->getCurrencySymbol(null,$_code); ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
