<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
USAGE:

Simple:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->toHtml() ?>

For checkout/onepage/shipping.phtml:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->setFieldIdFormat('shipping:%s')
   ->setFieldNameFormat('shipping[%s]')
   ->setFieldParams('onchange="shipping.setSameAsBilling(false);"')
   ->toHtml() ?>
*/
/* @var $block \Magento\Customer\Block\Widget\Name */
$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
?>

<?php if (($prefix || $middle || $suffix) && !$block->getNoWrap()): ?>
<div class="field required fullname <?php /* @escapeNotVerified */ echo $block->getContainerClassName() ?>">
    <label for="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>" class="label">
        <span><?php /* @escapeNotVerified */ echo __('Name') ?></span>
    </label>
    <div class="control">
        <fieldset class="fieldset fieldset-fullname">
        <div class="fields">
<?php endif; ?>

    <?php if ($prefix): ?>
        <div class="field field-name-prefix<?php if ($block->isPrefixRequired()) echo ' required' ?>">
            <div class="control">
                <?php if ($block->getPrefixOptions() === false): ?>
                    <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"
                           name="<?php /* @escapeNotVerified */ echo $block->getFieldName('prefix') ?>"
                           value="<?php echo $block->escapeHtml($block->getObject()->getPrefix()) ?>"
                           title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('prefix') ?>"
                           class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('prefix') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?>>
                <?php else: ?>
                        <?php foreach ($block->getPrefixOptions() as $_option): ?>
                            <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId('prefix') ?>"
                                   name="<?php /* @escapeNotVerified */ echo $block->getFieldName('prefix') ?>"
                                   class="<?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('prefix') ?>"
                                   type="radio"
                                   value="<?php /* @escapeNotVerified */ echo $_option ?>" <?php if ($block->getObject()->getPrefix() == $_option): ?> checked<?php endif; ?> <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> > <?php /* @escapeNotVerified */ echo __($_option) ?><br>
                        <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
        <div class="field field-name-firstname required">
            <div class="control">
                <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>"
                       name="<?php /* @escapeNotVerified */ echo $block->getFieldName('firstname') ?>"
                       placeholder="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>"
                       value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>"
                       class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('firstname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('firstname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
            </div>
        </div>
        <div class="field field-name-lastname required">
            <div class="control">
                <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>"
                       name="<?php /* @escapeNotVerified */ echo $block->getFieldName('lastname') ?>"
                       placeholder="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>"
                       value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>"
                       class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('lastname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('lastname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
            </div>
        </div>
    <?php if (($prefix || $middle || $suffix) && !$block->getNoWrap()): ?>
            </div>
        </fieldset>
    </div>
</div>
<?php endif; ?>
