<div class="col-sm-2 hidden-xs">
    <a href="/" class="logo">
        <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/logo_footer.png'); ?>"
             alt="<?php /* @escapeNotVerified */ echo \Magento\Framework\App\ObjectManager::getInstance()
                 ->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('design/header/logo_alt'); ?>"
        />
    </a>
</div>