<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>1): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
        <div class="actions dropdown options switcher-options col-sm-6">
            <div class="action toggle switcher-trigger dropdown-toggle" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
                <?php echo $block->escapeHtml($block->getStoreCode()) ?>
                <span class="caret"></span>
            </div>
            <ul class="dropdown switcher-dropdown dropdown-menu"
                data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":null}}'>
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                        <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                                <?php echo $block->escapeHtml($_lang->getCode()) ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
