<?php
 /*
 * @var $block \Credevlabz\Testimonials\Block\TestimonialsList 
 * @package Credevlabz/Testimonials
 * @author Aman Srivastava <http://amansrivastava.in>
 */ 
?>
<div class="testimonials">
<?php /** @var $testimonial \Credevlabz\Testimonials\Model\Testimonial */ ?>
<?php foreach ($block->getTestimonials() as $key => $testimonial): ?>
    <section id="testimonials_section_<?php echo $key;?>">
        <div class="container">
            <div class="col-xs-10 col-xs-offset-1 col-md-6 <?php echo ($key % 2 == 0) ? '' : 'col-md-offset-6';?>">
                <h2><?php echo $testimonial->getTitle(); ?></h2>
                <p><?php echo $testimonial->getContent(); ?></p>
                <span><?php echo $testimonial->getName(); ?></span>
            </div>
        </div>
        <?php if($testimonial->getCoverImage()): ?>
        <div class="bg-cover all-width" style="background-image: url('<?php echo "/pub/media/".$testimonial->getCoverImage(); ?>')"></div>
        <?php endif; ?>
    </section>
<?php endforeach; ?>
</div>
